/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    Bottom1: typeof import('./src/components/nav/Bottom1.vue')['default']
    Bread: typeof import('./src/components/coms/Bread.vue')['default']
    Button: typeof import('./src/components/coms/Button.vue')['default']
    Dir: typeof import('./src/components/ref/Dir.vue')['default']
    Events: typeof import('./src/components/ref/Events.vue')['default']
    Expan: typeof import('./src/components/coms/Expan.vue')['default']
    Expen: typeof import('./src/components/nav/Expen.vue')['default']
    Expend: typeof import('./src/components/nav/Expend.vue')['default']
    Fbutton: typeof import('./src/components/coms/Fbutton.vue')['default']
    Footers: typeof import('./src/components/coms/Footers.vue')['default']
    HelloWorld: typeof import('./src/components/coms/HelloWorld.vue')['default']
    Home: typeof import('./src/components/coms/Home.vue')['default']
    Latout2: typeof import('./src/components/layout/Latout2.vue')['default']
    Latout3: typeof import('./src/components/layout/Latout3.vue')['default']
    LatoutTwo: typeof import('./src/components/layout/LatoutTwo.vue')['default']
    Layout1: typeof import('./src/components/layout/Layout1.vue')['default']
    Layout2: typeof import('./src/components/layout/Layout2.vue')['default']
    Layout3: typeof import('./src/components/layout/Layout3.vue')['default']
    LayoutOne: typeof import('./src/components/layout/LayoutOne.vue')['default']
    Nav1: typeof import('./src/components/nav/Nav1.vue')['default']
    Nav2: typeof import('./src/components/nav/Nav2.vue')['default']
    Nav3: typeof import('./src/components/nav/Nav3.vue')['default']
    Nav4: typeof import('./src/components/nav/Nav4.vue')['default']
    Nav5: typeof import('./src/components/nav/Nav5.vue')['default']
    Page: typeof import('./src/components/coms/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./src/components/coms/Tabs.vue')['default']
    Tooltip: typeof import('./src/components/coms/Tooltip.vue')['default']
    Tooltips: typeof import('./src/components/coms/Tooltips.vue')['default']
  }
}
